# Generated by Django 3.2.16 on 2022-12-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='wards',
            fields=[
                ('wardno', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('wardname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='wastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=200)),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='wastecollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('phoneno', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=1000)),
                ('wardno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.wards')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phoneno', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='collectionstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=200, null=True)),
                ('collection_date', models.DateField(null=True)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.employee')),
                ('wardno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.wards')),
            ],
        ),
    ]
