# Generated by Django 3.2.16 on 2022-12-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CorporationApp', '0002_employee_roles_wastecollector'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectionstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardno', models.BigIntegerField()),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.employee')),
            ],
        ),
    ]
