# Generated by Django 3.2.16 on 2022-12-04 07:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CorporationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='houseowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phoneno', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=50)),
                ('wardno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.wards')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('roleid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='slotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('houseowner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseOwnerApp.houseowner')),
                ('waste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.wastes')),
            ],
        ),
        migrations.CreateModel(
            name='bookingstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('collection_date', models.DateField(null=True)),
                ('booking_date', models.DateField()),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseOwnerApp.slotbooking')),
                ('wastecollector_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CorporationApp.wastecollector')),
            ],
        ),
    ]
